### ISSUE TITLE
Influence des lots aléatoires sur le jugement majoritaire

### ISSUE THREAD

**Issue by ghost** [democratech/LaPrimaire#42]
Je me demande si le système de vote que vous avez retenu, jugement majoritaire + lots aléatoires de candidats, sera aussi efficace qu'on le pense.

Pour moi, le jugement majoritaire ne fonctionne correctement que si on peut définir **une échelle commune** dans laquelle on puisse évaluer "objectivement" chaque candidat. L'idée c'est que, si un candidat "vaut" telle mention, la majorité la lui attribuera même s'il y a une minorité qui vote de manière stratégique, ce qui assure un classement juste.

Mon problème avec les lots aléatoires, c'est qu'il n'y a plus forcément d'échelle commune. On pourrait le vérifier en demandant à un électeur de gauche d'évaluer Hollande et Montebourg, il voudrait peut-être attribuer la mention "Insuffisant" à l'un des deux ; mais si on posait la même question en rajoutant Le Pen, les deux candidats de gauche seraient sans doute notés "Passable" ou mieux pour réserver la plus mauvaise mention à la candidate d'extrême-droite.

À mon avis, le choix des mentions dépend donc de la composition des lots aléatoires. Le paradoxe qu'on risque alors bien de voir, c'est qu'un candidat A pourrait être préféré à un candidat B par une majorité des électeurs les ayant eu tous les deux dans leurs panels et pourtant se retrouver moins bien classé à cause du jugement des autres électeurs.

J'espère que les données du vote seront publiées, pour vérifier si on y trouve ce paradoxe.

**Comment by thibauld** [comment]
Justement, la distribution aléatoire des candidats dans les lots fait que tous les cas de figure seront présents : dans certains cas, des candidats seront peut être avantagés et mais cela est compensé par les autres cas de figure dans lesquels ils seront désavantagés, c'est la toute la force du tirage aléatoire. Enfin, pour information, nous échangeons régulièrement avec l'inventeur du jugement majoritaire qui ne soulève aucun problème théorique sur cette approche.

**Comment by ghost** [comment]
Je ne suis pas sûr que cela sera forcément bien compensé… j'étudierai ce qu'il en est en situation réelle dans deux jours. Merci pour votre réponse en tout cas !

**Comment by ghost** [comment]
Ah, malheureusement les cinq votes de chaque votant ne sont pas liés entre eux, on ne pourra donc pas analyser l'influence de la composition des lots sur les votes… dommage :-(

**Comment by thibauld** [comment]
Quel dommage d'utiliser sans cesse ce ton qui part du principe que nous sommes incompétents, sournois et/ou mûs d'une volonté de tromper les gens... ça ne donne vraiment pas envie de répondre :/ Comme vous avez pu le constater via les réponses sur le forum MaVoix, il n'y a ni volonté de tromper les gens, ni volonté de cacher quoique ce soit. Pourquoi cherchez-vous à nous dénigrer sans cesse ? On vous a fait quelque chose ? Si vous n'aimez pas LaPrimaire.org, je peux tout à fait l'entendre, y a aucun souci mais dans ce cas, je vous invites simplement à essayer de faire mieux ou à soutenir un projet qui vous semble plus prometteur, ce sera plus immensément plus constructif.

**Comment by ghost** [comment]
Oui Jean-Marc Le Roux a eu la patience de discuter des limites du vote électronique utilisé, merci à lui d'ailleurs. Concernant le système de vote, j'ai l'impression que, comme il y avait 5 candidats par lot et 5 mentions possibles, beaucoup de votants les ont classés les uns par rapport aux autres ; le hasard de la distribution des lots pourrait donc avoir eu plus d'importance que ce qu'on pense. Quel dommage de ne pas pouvoir le vérifier ! Encore merci pour votre fabuleux travail en tout cas.
