### ISSUE TITLE
Reconnaissance du vote blanc

### ISSUE THREAD

**Issue by ghost** [democratech/LaPrimaire#46]
LaPrimaire.org veut organiser des primaires « 100 % démocratiques » et a pour cela adopté un mode de scrutin qui se veut innovant, mais elle a oublié un enjeu démocratique majeur : la reconnaissance du vote blanc, comme suffrage exprimé à part entière.

Ce serait une bonne idée, pour de prochaines élections, d'ajouter à la liste des candidats déclarés une nouvelle option « Blanc : si le vote blanc obtient la meilleure mention majoritaire, alors LaPrimaire.org ne soutiendra aucune candidature. »

**Comment by arncav** [comment]
M. BODIN

Le ton de votre message ne me paraît pas personnellement sain.

J'apprécierai l arrêt des messages de cette nature.

Vous avez la liberté et la possibilité de faire mieux que laprimaire que vous critiquez... n hésitez pas... mais laissez nous tranquilles.
 
Certes, la reconnaissance du vote dans dans le système binaire dans laquelle la France vit est une nécessité absolue.

Laprimaire.org a déjà fait beaucoup évolué le vote, et le chemin est encore long... personne ne prétend que c'est un système parfait. 

Les votants à laprimaire ne cherchent pas à imposer un type de scrutin pour la France. Si vous trouvez qu'aucun candidat ne mérite votre évaluation, passez votre chemin, faites mieux ailleurs mais arrêtez vos messages inadaptés.

Arnaud





Le 8 janvier 2017 04:00:47 GMT+01:00, "Gérard Bodin" <notifications@github.com> a écrit :
>LaPrimaire.org veut organiser des primaires « 100 % démocratiques » et
>a pour cela adopté un mode de scrutin qui se veut innovant, mais elle a
>occulté un enjeu démocratique majeur : la reconnaissance du vote blanc,
>comme suffrage exprimé à part entière.
>
>Ce serait une bonne idée, pour de prochaines élections, d'ajouter à la
>liste des candidats déclarés une nouvelle option « Blanc : si le vote
>blanc obtient la meilleure mention majoritaire, alors LaPrimaire.org ne
>soutiendra aucune candidature. »
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/democratech/LaPrimaire/issues/46


Amicalement,
Arnaud
06.78.36.95.79

**Comment by ghost** [comment]
Monsieur Arnaud,

Vous reconnaissez vous-même la « nécessité absolue de la reconnaissance du vote blanc » donc mon message n'est pas inadapté, il traduit ce que, vous aussi, vous désirez pour notre pays.

Mais je comprends très bien que cette ambition démocratique puisse vous effrayer. Au début de la Primaire.org, democratech non plus n'osait pas et défendait encore le vote majoritaire comme mode de scrutin. Heureusement, on ne s'est pas laissé intimider par les conservatismes et on a osé, ce qui a conduit au succès que vous soulignez : LaPrimaire.org, avec d'autres, a rouvert le débat du mode de scrutin en France. C'est cela [l'esprit collaboratif](https://laprimaire.org/charte/) de LaPrimaire.org !

Personnellement je ne baisse donc pas les bras, et puisque vous êtes de mon avis je vous invite à soutenir cette idée. Vous pourriez par exemple m'aider en reformulant cette suggestion avec un ton qui vous semble meilleur :smile:
